apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: tenants.tbird.vista.co
spec:
  group: tbird.vista.co
  version: "v1alpha1"
  scope: Namespaced  
  names:
    kind: Tenant
    listKind: TenantList
    plural: tenants
    singular: tenant

  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            alias:
              type: string

